apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      volumes:
      - name: host-app
        hostPath:
          path: /app
      containers:
      - name: helloworld
        image: dockerhw:0.1.0
        volumeMounts:
        - name: host-app
          mountPath: /app
      nodeSelector:
        app: helloworld
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
  - name: http
    port: 80
    nodePort: 30951
    targetPort: 80
