apiVersion: apps/v1
kind: Deployment
metadata:
  name: whome
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whome
  template:
    metadata:
      labels:
        app: whome
    spec:
      volumes:
      - name: host-app
        hostPath:
          path: /app
      containers:
      - name: whome
        image: dockerwhome:0.1.0
        volumeMounts:
        - name: host-app
          mountPath: /app
      nodeSelector:
        app: whome
---
apiVersion: v1
kind: Service
metadata:
  name: whome
spec:
  type: NodePort
  selector:
    app: whome
  ports:
  - name: http
    port: 80
    nodePort: 30950
    targetPort: 80
